# -*- coding: utf-8 -*-
"""0905_파이썬으로 adafruit에 값 보내기.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EisqjZWwyNembP0rBLnsWm5Pq2_zyvGZ
"""

pip install adafruit-io #adafruit-io 라이브러리 설치해야 됨

from Adafruit_IO import RequestError, Client, Feed

Adafruit_IO_USER = 'Ur User Name' #자기 adafruit user name 입력
Adafruit_IO_KEY = 'Ur KEY' #자기 adafruit io key 입력

aio = Client(Adafruit_IO_USER,Adafruit_IO_KEY) #client 생성

feeds = aio.feeds()
print(feeds) # 이건 그냥 갖고 있는 피드들 확인하는 거!

try:
  test = aio.feeds('test')#test라는 피드를 받아 온다
except RequestError : 
  test_feed = Feed(name = 'test')
  print(feeds)
  test_feed = aio.create_feed(test_feed)

#test 피드에 값 넣기
aio.send_data(test.key, 4)
aio.send_data(test.key, 16)
aio.send_data(test.key,32)

cur = aio.receive('test').value #test 피드에서 최근 값 받아옴
print(cur)
