 # -*- coding: utf-8 -*-
"""robotics_final.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1h0wQ0hIJTE-VB6sn7Qluo9nxFaQR01F3
"""

from google.colab import drive



import pandas as pd

from Adafruit_IO import RequestError, Client, Feed


if __name__ == "__main__":

  firekey = []
  smokekey = []
  ledkey = []
  
  firename=[]
  smokename=[]
  ledname=[]

  Adafruit_IO_USER = 'Jiwon1121'
  Adafruit_IO_KEY = "aio_QLCh78pflpzTzUCAJPizUc0qxzZv"

  aio = Client(Adafruit_IO_USER,Adafruit_IO_KEY)

  feeds = aio.feeds()

  aio.send_data(fire00.key, 0)
  aio.send_data(smoke00.key, 0)
  aio.send_data(fire01.key, 0)
  aio.send_data(smoke01.key, 0)
  aio.send_data(fire02.key, 0)
  aio.send_data(smoke02.key, 0)
  aio.send_data(fire03.key, 0)
  aio.send_data(smoke03.key, 0)
  aio.send_data(fire04.key, 0)
  aio.send_data(smoke04.key, 0)
  aio.send_data(fire05.key, 0)
  aio.send_data(smoke05.key, 0)
  aio.send_data(fire06.key, 0)
  aio.send_data(smoke06.key, 0)
  aio.send_data(fire07.key, 0)
  aio.send_data(smoke07.key, 0)
  aio.send_data(fire08.key, 0)
  aio.send_data(smoke08.key, 0)
  aio.send_data(fire09.key, 0)
  aio.send_data(smoke09.key, 0)
  aio.send_data(fire10.key, 0)
  aio.send_data(smoke10.key, 0)
  aio.send_data(fire11.key, 0)
  aio.send_data(smoke11.key, 0)
  aio.send_data(fire12.key, 0)
  aio.send_data(smoke12.key, 0)
  aio.send_data(fire13.key, 0)
  aio.send_data(smoke13.key, 0)
  aio.send_data(fire14.key, 0)
  aio.send_data(smoke14.key, 0)
  aio.send_data(fire15.key, 0)
  aio.send_data(smoke15.key, 0)
  aio.send_data(fire16.key, 0)
  aio.send_data(smoke16.key, 0)
  aio.send_data(fire17.key, 0)
  aio.send_data(smoke17.key, 0)
  aio.send_data(fire18.key, 0)
  aio.send_data(smoke18.key, 0)
  aio.send_data(fire19.key, 0)
  aio.send_data(smoke19.key, 0)
  aio.send_data(fire20.key, 0)
  aio.send_data(smoke20.key, 0)
  aio.send_data(fire21.key, 0)
  aio.send_data(smoke21.key, 0)
  aio.send_data(fire22.key, 0)
  aio.send_data(smoke22.key, 0)
  aio.send_data(fire23.key, 0)
  aio.send_data(smoke23.key, 0)
