# -*- coding: utf-8 -*-
"""0908_파이썬으로 adafruit에 값 보내기.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EisqjZWwyNembP0rBLnsWm5Pq2_zyvGZ
"""

pip install adafruit-io

from Adafruit_IO import RequestError, Client, Feed
import time #sleep 시키기 위해서

Adafruit_IO_USER = 'User Name'
Adafruit_IO_KEY = 'User Key'

aio = Client(Adafruit_IO_USER,Adafruit_IO_KEY) #client 생성

feeds = aio.feeds()

try:
  #print(feeds)
  smoke = aio.feeds('smoke') #키 값 이용해서 feed 받아오는 객체 생성
except RequestError : 
  test_feed = Feed(name = 'Smoke') #Smoke을 이름으로 한 feed 생성
  print(feeds)
  test_feed = aio.create_feed(test_feed)

#aio.send_data(smoke.key, 4) #test

while(1):
  cur = aio.receive('smoke').value #키값으로!
  time.sleep(5)
  if (cur=='nan'):
    cur = 0
  print(cur)
  if (float(cur)>300): #LED 피드에 1값을 보내 led 킬 수 있도록
    led = aio.feeds('led')
    print("I'm here")
    aio.send_data(led.key,1)

##피드의 키 값은 피드 이름의 소문자 ! ex) ABCD 피드의 키 값은 abcd
